version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - "SMAKSS"
    assignees:
      - "SMAKSS"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
