name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Print head and base refs
      run: |
        echo "Head ref: ${{ github.head_ref }}"
        echo "Base ref: ${{ github.base_ref }}"

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-node-18-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-18-yarn-

    - name: Install dependencies
      run: yarn install

    - name: Type check
      run: yarn typecheck

    - name: Check code quality
      run: |
        yarn lint
        yarn format:check
        yarn run --if-present generate

    - name: Security Audit
      run: yarn audit --level moderate || true
      continue-on-error: true

    - name: Security Audit Summary
      if: success() || failure()
      run: yarn audit --summary

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ./build/

    - name: Error handling
      if: failure()
      run: echo "CI failed. Please check the logs."
